version: 2

jobs:
    build:
        docker:
            - image: circleci/node:12-browsers

        steps:
            - checkout

            # Download and cache dependencies
            - restore_cache:
                keys:
                    - v2-dependencies-{{ checksum "package.json" }}
                    # fallback to using the latest cache if no exact match is found
                    - v2-dependencies-

            - run: npm install
            - run: ./node_modules/.bin/cypress install

            # save cache
            - save_cache:
                paths:
                    - ./node_modules
                    - ~/.cache/Cypress
                key: v2-dependencies-{{ checksum "package.json" }}


            # RUN
            - run:
                name: Build
                command: npm run-script build
            - run:
                name: npm audit
                command: npm audit
            - run:
                name: Prettier package.json
                command: npx prettier-package-json package.json --list-different --tab-width 4
            - run:
                name: npm test
                command: npm test


workflows:
    version: 2
    all:
        jobs:
            - build
